tasks:
  - name: Adding dependencies
    command: npm i -g nodemon && npm i -g expo-cli && clear

vscode:
  extensions:
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
    - naumovs.color-highlight

ports:
  - port: 3000
    onOpen: ignore
    visibility: public

  - port: 8081
    onOpen: open-preview
    visibility: public
